version: "3"
services:
  elk:
    image: sebp/elk
    restart: "always"
    build:
      context: ./elk
      dockerfile: Dockerfile
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
      - "31311:31311"
